name: 'Prefect Cloud agent on Compute Engine'
branding:
  icon: cloud
  color: blue
description: 'Test action'
inputs:
  prefect_api_key:
    description: 'Prefect Cloud API key'
    required: true
  prefect_api_url:
    description: 'Prefect Cloud API URL'
    required: true
  gcp_project_id:
    description: 'Name of the GCP Project ID'
    required: true
  gcp_sa_email:
    description: 'Email of the Service Account'
    required: true
  gcp_credentials_json:
    description: 'Content of the Service Account JSON key file'
    required: true
  region:
    description: 'GCP region'
    required: false
    default: 'us-east1'
  zone:
    description: 'GCP region with the zone'
    required: false
    default: 'us-east1-b'
  machine_type:
    description: 'GCP Compute Engine instance type'
    required: false
    default: 'e2-micro'
  machine_name:
    description: 'GCP Compute Engine instance name'
    required: false
    default: 'prefect-vm'
  artifact_repository:
    description: 'Artifact Registry Repository Name'
    required: false
    default: prefect
  github_block_name:
    description: 'Name of the GitHub block'
    required: false
    default: default

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - id: install-prefect
      run: pip install prefect
      shell: bash

    - id: login-prefect
      run: |
        prefect config set PREFECT_API_KEY=${{ inputs.prefect_api_key }}
        prefect config set PREFECT_API_URL=${{ inputs.prefect_api_url }}
      shell: bash

    - id: create-blocks
      run: |
        cat <<EOF > blocks.py
        from prefect.filesystems import GitHub
        gh = GitHub(repository="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY", reference="$GITHUB_REF_NAME")
        gh.save("${{ inputs.github_block_name }}", overwrite=True)
        EOF
        python blocks.py
      shell: bash

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ inputs.gcp_credentials_json }}"

    - id: repository
      run: gcloud artifacts repositories create ${{ inputs.artifact_repository }} --repository-format=docker --location=${{ inputs.region }}
      continue-on-error: true
      shell: bash

    - id: image
      run: echo "IMAGE_URI=${{ inputs.region }}-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.artifact_repository }}/agent:$GITHUB_SHA" >> $GITHUB_ENV
      shell: bash

    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: '${{ inputs.region }}-docker.pkg.dev'
        username: _json_key
        password: ${{ inputs.gcp_credentials_json }}

    - id: build-image
      run: |
        docker build --build-arg PREFECT_API_KEY=${{ inputs.prefect_api_key }} --build-arg PREFECT_API_URL=${{ inputs.prefect_api_url }} -t "${{ env.IMAGE_URI }}" -f Dockerfile.agent .
        docker push "${{ env.IMAGE_URI }}"
      shell: bash

    - id: delete
      run: gcloud compute instances delete "${{ inputs.machine_name }}" --zone "${{ inputs.zone }}" --quiet
      continue-on-error: true
      shell: bash

    - id: deploy
      shell: bash
      run: |
        gcloud compute instances create-with-container "${{ inputs.machine_name }}" \
          --zone "${{ inputs.zone }}" \
          --machine-type "${{ inputs.machine_type }}" \
          --service-account "${{ inputs.gcp_sa_email }}" \
          --scopes "cloud-platform" \
          --container-image "${{ env.IMAGE_URI }}"
